### ISSUE TITLE
Shift Batch

### ISSUE THREAD

**Issue by juliavisserinbibo** [Inbibo/shift_docs#12]
This issue addresses the content of the Shift Batch page. aims to show the user how to execute a shift workflow without need of using the UI. This should include

- Explanation of the requirements to launch shift batch
- Workflow execution from the terminal
  - Execute commands
  - Ouput interpretation
- Workflow execution from a python script
  - Shift modules for python
  - Shift methods for workflow execution
  - Output interpretation
 
Screenshots and new section pages should be added where necessary.

**Comment by albertochimentiinbibo** [comment]
waiting on completion of https://github.com/Inbibo/shift/issues/1112#issue-2487182356

**Comment by albertochimentiinbibo** [comment]
Updated with the changes made by https://github.com/Inbibo/shift/pull/1115
