### ISSUE TITLE
UI Overview

### ISSUE THREAD

**Issue by juliavisserinbibo** [Inbibo/shift_docs#7]
This issue addresses the content of the UI overview page. This page is intended to provide an explanation of the Shift UI, including:
- Top bar menu 
- Workflow actions tool bar
- Shift Board
- Fixed widgets
  - Inspector
  - Node List
  - Logger (just an overview, this will be explained in more detail in another section)

Screenshots should be added where necessary.

**Comment by juliavisserinbibo** [comment]
When we open Shift for the first time, this is the layout disposition the user will see. 

![Image](https://github.com/user-attachments/assets/5a35801e-35b7-4cc3-b3ac-2839307e6b10)

I'm used to having the inspector on the right and the logger at the bottom, andI believe this is the typical setup for other similar software to Shift. Additionally, the initial size of the Shift App makes the board size a bit small, cutting off the Shift logo at the top and bottom.

The way I inspected the initial state of Shift is by removing the logic to restore the widgets layout disposition for the Window Preferences in Shift. I basically commented these lines from the `main.py` file:
```
      settings = QtCore.QSettings("Inbibo", "Shift")
      self.restoreGeometry(settings.value("geometry"))
      self.restoreState(settings.value("windowState"))
```


As the current layout disposition doesn't feel natural, we must vote for a new default layout. In the following comments I will add some proposals. 

REACT WITH 👍 ON THE PROPOSAL YOU FIND BEST SUITED

**Comment by juliavisserinbibo** [comment]
**PROPOSAL 2**

![Image](https://github.com/user-attachments/assets/a77c5160-2bf3-424c-bad2-0319788d1483)

**Comment by juliavisserinbibo** [comment]
**PROPOSAL 3**

![Image](https://github.com/user-attachments/assets/433f20c5-436d-4dfd-b8db-a245a4d66fa3)

**Comment by mromeoinbibo** [comment]
I like Proposal 2.
It is exactly what I would have proposed, so no need for me to add my own proposal.
