### ISSUE TITLE
Workflow Authoring

### ISSUE THREAD

**Issue by juliavisserinbibo** [Inbibo/shift_docs#8]
This issue addresses the content of the Workflow Authoring  page. This page aims to drive the user through the creation of a straightforward workflow that will enable them to understand the most basic features of Shift workflows, including:
- Creating a new node
- Creating a new plug
- Connecting two nodes through their plugs
- Save the workflow.

Screenshots should be added where necessary.

Notes:
- Terminology will be properly linked when that page is finished. 
- The Node List widget will be properly linked when the UI Overview page is finished.

**Comment by juliavisserinbibo** [comment]
A question by @JorgeHernandezibanezinbibo  has been raised in the PR.
https://github.com/Inbibo/shift_docs/pull/25#discussion_r1721800376

Basically, the documentation states that two plugs with the same name can coexist in a node as long as they belong to different plug directions. While this is true, as it is what allows `through` plugs to exist, at the same time the Add Dialog won't allow creating an input plug with a name and then and output plug with the same name. This is because the check for the unique code names is global to the node, and not to the plug direction.

We have to decide as a team if this is the expected behavior or, in the contrary, if we want to change it to allow two plugs with the same name to be created separately as an input and then as an output. 

@Inbibo/shift

**Comment by albertochimentiinbibo** [comment]
@juliavisserinbibo for me it is a good change to have, however, in order to put it in place we would have to change the blacklist data passed to the AddPlugDialog and add logic to check the selected direction and change the blacklist depending on whether it is an in or an out. Also for kThrough direction we should make a set of the two lists and check for that. Do you have an opinion on how involved this could be?

**Comment by juliavisserinbibo** [comment]
> [@juliavisserinbibo](https://github.com/juliavisserinbibo) for me it is a good change to have, however, in order to put it in place we would have to change the blacklist data passed to the AddPlugDialog and add logic to check the selected direction and change the blacklist depending on whether it is an in or an out. Also for kThrough direction we should make a set of the two lists and check for that. Do you have an opinion on how involved this could be?

I implemented the change sin this PR, please have a look
